### ISSUE TITLE
MySQL: Buyer order logic

### ISSUE THREAD

**Issue by LaansDole** [miketvo/rmit-isys2099-group9-app#22]
## Add to Cart and Place orders 

- Must check the product inventory to see ***if there are enough products to sell***
- Must use ***transaction & concurrency techniques*** to ensure the validity of orders (for example, if there is only one product item left, but two customers place orders for that product at the same time, only one can be successful). 
- Testing Isolation level of orders' transaction

**Comment by miketvo** [comment]
Done
