### ISSUE TITLE
MySQL: Buyer order fulfillment simulation

### ISSUE THREAD

**Issue by LaansDole** [miketvo/rmit-isys2099-group9-app#23]
## Simulate the order delivery on the ***client-mall side***

In the client-mall interface, for each placed order, there are two buttons: Accept and Reject. 
- If this is an Accept, update the inventory information. 
- If it is a Reject, send back the products in the buyer's order to the appropriate warehouses. Use triggers (combined with stored procedures) to automate the inventory update once an order status is updated to Accept or Reject.

**Comment by miketvo** [comment]
Done
